[package]
name = "assignment1"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
chrono = "0.4.38"
clap = { version = "4.2", features = ["derive"] }
csv = "1.3.1"
prost = "0.13.3"
serde = { version = "1.0", features = ["derive"] }



